== Design

=== Overview

The Digital Identities system will utilize a client-server architecture.


=== Component Roles

*Server:*

A REST API that handles all requests for user login, token generation and token validation.

*Client:*

A web application that interacts with the server API. The client generates the required payloads and sends them via AJAX request.

*Database:*

Persistent data storage. The user login data is stored in the database and used for token validation.


=== High Level Diagram

[plantuml]
....

@startuml Digital Identities
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(authority, "Authority")
Person(user, "User")

System_Boundary(c1, "Digital Identities") {
    Container(web_app, "Web Application", "JavaScript, HTML, CSS", "Allows Authentication and Validation")
    Container(api, "API", "Python, FastAPI", "Manages validation of authentication requests, handles database")
    Container(database, "Database", "JSON File Store", "Allows storage of user credentials")
}

Rel_R(authority, web_app, "Validates with QR code")
Rel_L(user, web_app, "Generates a QR Code")
Rel(web_app, api, "Validate Token/User")
Rel(api, database, "Set/Get Creds")
@enduml
....

